services:
  backend:
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
      target: $ENV_MODE
    container_name: guss_game_backend
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - ./apps/server:/app/apps/server
      - ./shared:/app/shared
      - /app/node_modules  # Prevent host/node_modules collision

  db:
    build:
      context: ./apps/server/db
    container_name: guss_game_db
    # restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
      target: $ENV_MODE
    container_name: guss_game_frontend
    env_file:
      - .env
    ports:
      - '8080:3001'
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
